// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: querier.proto

/*
Package userBalance is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package userBalance

import (
	"context"
	"io"
	"net/http"

	"github.com/golang/protobuf/descriptor"
	"github.com/golang/protobuf/proto"
	"github.com/grpc-ecosystem/grpc-gateway/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/status"
)

// Suppress "imported and not used" errors
var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray
var _ = descriptor.ForMessage

var (
	filter_UserBalanceQueryService_BatchUserAssets_0 = &utilities.DoubleArray{Encoding: map[string]int{}, Base: []int(nil), Check: []int(nil)}
)

func request_UserBalanceQueryService_BatchUserAssets_0(ctx context.Context, marshaler runtime.Marshaler, client UserBalanceQueryServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq BatchUserAssetsParams
	var metadata runtime.ServerMetadata

	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_UserBalanceQueryService_BatchUserAssets_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.BatchUserAssets(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_UserBalanceQueryService_BatchUserAssets_0(ctx context.Context, marshaler runtime.Marshaler, server UserBalanceQueryServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq BatchUserAssetsParams
	var metadata runtime.ServerMetadata

	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_UserBalanceQueryService_BatchUserAssets_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.BatchUserAssets(ctx, &protoReq)
	return msg, metadata, err

}

// RegisterUserBalanceQueryServiceHandlerServer registers the http handlers for service UserBalanceQueryService to "mux".
// UnaryRPC     :call UserBalanceQueryServiceServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
func RegisterUserBalanceQueryServiceHandlerServer(ctx context.Context, mux *runtime.ServeMux, server UserBalanceQueryServiceServer) error {

	mux.Handle("GET", pattern_UserBalanceQueryService_BatchUserAssets_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateIncomingContext(ctx, mux, req)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_UserBalanceQueryService_BatchUserAssets_0(rctx, inboundMarshaler, server, req, pathParams)
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_UserBalanceQueryService_BatchUserAssets_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

// RegisterUserBalanceQueryServiceHandlerFromEndpoint is same as RegisterUserBalanceQueryServiceHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterUserBalanceQueryServiceHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.Dial(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterUserBalanceQueryServiceHandler(ctx, mux, conn)
}

// RegisterUserBalanceQueryServiceHandler registers the http handlers for service UserBalanceQueryService to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterUserBalanceQueryServiceHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterUserBalanceQueryServiceHandlerClient(ctx, mux, NewUserBalanceQueryServiceClient(conn))
}

// RegisterUserBalanceQueryServiceHandlerClient registers the http handlers for service UserBalanceQueryService
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "UserBalanceQueryServiceClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "UserBalanceQueryServiceClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "UserBalanceQueryServiceClient" to call the correct interceptors.
func RegisterUserBalanceQueryServiceHandlerClient(ctx context.Context, mux *runtime.ServeMux, client UserBalanceQueryServiceClient) error {

	mux.Handle("GET", pattern_UserBalanceQueryService_BatchUserAssets_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateContext(ctx, mux, req)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_UserBalanceQueryService_BatchUserAssets_0(rctx, inboundMarshaler, client, req, pathParams)
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_UserBalanceQueryService_BatchUserAssets_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

var (
	pattern_UserBalanceQueryService_BatchUserAssets_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 2, 3, 2, 4}, []string{"v1", "balance", "assets", "user", "batch"}, "", runtime.AssumeColonVerbOpt(true)))
)

var (
	forward_UserBalanceQueryService_BatchUserAssets_0 = runtime.ForwardResponseMessage
)
